### ISSUE TITLE
Rounding of "interested" box is incorrect

### ISSUE THREAD

**Issue by cwbmuller** [salthq/Alf-Public#1]
## Context

The rounding of the bottom of the "interested in partnering with us box is off", see image below"

![Screenshot 2022-05-17 at 12 18 41](https://user-images.githubusercontent.com/1436311/168791154-47ff3c3b-1dbe-40d2-8cb8-bce09a68003a.png)

**Comment by Nicholasbell03** [comment]
@cwbmuller finally got alf up on the new MacBook. Gonna try resolve this today

**Comment by Nicholasbell03** [comment]
This was resolved around 2 weeks ago.
